### 브랜드 등록 - 성공 케이스
POST {{commerce-api}}/api-admin/v1/brands
Content-Type: application/json
X-Loopers-Ldap: loopers.admin

{
  "name": "나이키"
}

### 브랜드 등록 - 브랜드명 빈값 (실패)
POST {{commerce-api}}/api-admin/v1/brands
Content-Type: application/json
X-Loopers-Ldap: loopers.admin

{
  "name": ""
}

### 브랜드 등록 - LDAP 헤더 누락 (실패 - 401)
POST {{commerce-api}}/api-admin/v1/brands
Content-Type: application/json

{
  "name": "나이키"
}

### 브랜드 등록 - 잘못된 LDAP 헤더 (실패 - 401)
POST {{commerce-api}}/api-admin/v1/brands
Content-Type: application/json
X-Loopers-Ldap: wrong.value

{
  "name": "나이키"
}

### 브랜드 목록 조회 - 기본 페이지
GET {{commerce-api}}/api-admin/v1/brands?page=0&size=20
X-Loopers-Ldap: loopers.admin

### 브랜드 목록 조회 - 페이지 크기 지정
GET {{commerce-api}}/api-admin/v1/brands?page=0&size=2
X-Loopers-Ldap: loopers.admin

### 브랜드 상세 조회
GET {{commerce-api}}/api-admin/v1/brands/1
X-Loopers-Ldap: loopers.admin

### 브랜드 상세 조회 - 존재하지 않는 브랜드 (실패)
GET {{commerce-api}}/api-admin/v1/brands/999
X-Loopers-Ldap: loopers.admin

### 브랜드 수정 - 성공 케이스
PUT {{commerce-api}}/api-admin/v1/brands/1
Content-Type: application/json
X-Loopers-Ldap: loopers.admin

{
  "name": "아디다스"
}

### 브랜드 수정 - 브랜드명 빈값 (실패)
PUT {{commerce-api}}/api-admin/v1/brands/1
Content-Type: application/json
X-Loopers-Ldap: loopers.admin

{
  "name": ""
}

### 브랜드 삭제 - 성공 케이스
DELETE {{commerce-api}}/api-admin/v1/brands/1
X-Loopers-Ldap: loopers.admin

### 브랜드 삭제 - 존재하지 않는 브랜드 (실패)
DELETE {{commerce-api}}/api-admin/v1/brands/999
X-Loopers-Ldap: loopers.admin
