### 상품 목록 조회 - 기본
GET {{commerce-api}}/api/v1/products?page=0&size=20

### 상품 목록 조회 - 브랜드 필터링
GET {{commerce-api}}/api/v1/products?brandId=1&page=0&size=20

### 상품 목록 조회 - 가격 낮은순 정렬
GET {{commerce-api}}/api/v1/products?sort=price_asc&page=0&size=20

### 상품 목록 조회 - 좋아요 많은순 정렬
GET {{commerce-api}}/api/v1/products?sort=likes_desc&page=0&size=20

### 상품 목록 조회 - 페이지 크기 지정
GET {{commerce-api}}/api/v1/products?page=0&size=2

### 상품 상세 조회
GET {{commerce-api}}/api/v1/products/1

### 상품 상세 조회 - 존재하지 않는 상품 (실패)
GET {{commerce-api}}/api/v1/products/999
