server:
  port: 8082

management:
  server:
    port: 8083

spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create

datasource:
  mysql-jpa:
    main:
      jdbc-url: jdbc:mysql://mysql:3306/paymentgateway
      username: application
      password: application

spring.data.redis:
  host: redis-master
  port: 6379
